/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AvisoDeAfiliadosRouteImport } from './routes/aviso-de-afiliados'
import { Route as ComoPesquisamosRouteImport } from './routes/como-pesquisamos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PoliticaDeCookiesRouteImport } from './routes/politica-de-cookies'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ArtigosIndexRouteImport } from './routes/artigos.index'
import { Route as ArtigosSlugRouteImport } from './routes/artigos.$slug'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoDeAfiliadosRoute = AvisoDeAfiliadosRouteImport.update({
  id: '/aviso-de-afiliados',
  path: '/aviso-de-afiliados',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoPesquisamosRoute = ComoPesquisamosRouteImport.update({
  id: '/como-pesquisamos',
  path: '/como-pesquisamos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeCookiesRoute = PoliticaDeCookiesRouteImport.update({
  id: '/politica-de-cookies',
  path: '/politica-de-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const ArtigosIndexRoute = ArtigosIndexRouteImport.update({
  id: '/artigos/',
  path: '/artigos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtigosSlugRoute = ArtigosSlugRouteImport.update({
  id: '/artigos/$slug',
  path: '/artigos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/aviso-de-afiliados': typeof AvisoDeAfiliadosRoute
  '/como-pesquisamos': typeof ComoPesquisamosRoute
  '/contato': typeof ContatoRoute
  '/mcp': typeof McpRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/login': typeof AdminLoginRoute
  '/artigos/$slug': typeof ArtigosSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/artigos/': typeof ArtigosIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/aviso-de-afiliados': typeof AvisoDeAfiliadosRoute
  '/como-pesquisamos': typeof ComoPesquisamosRoute
  '/contato': typeof ContatoRoute
  '/mcp': typeof McpRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/login': typeof AdminLoginRoute
  '/artigos/$slug': typeof ArtigosSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/admin': typeof AdminIndexRoute
  '/artigos': typeof ArtigosIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/aviso-de-afiliados': typeof AvisoDeAfiliadosRoute
  '/como-pesquisamos': typeof ComoPesquisamosRoute
  '/contato': typeof ContatoRoute
  '/mcp': typeof McpRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/login': typeof AdminLoginRoute
  '/artigos/$slug': typeof ArtigosSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/artigos/': typeof ArtigosIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/aviso-de-afiliados'
    | '/como-pesquisamos'
    | '/contato'
    | '/mcp'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/login'
    | '/artigos/$slug'
    | '/categoria/$slug'
    | '/admin/'
    | '/artigos/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/aviso-de-afiliados'
    | '/como-pesquisamos'
    | '/contato'
    | '/mcp'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/login'
    | '/artigos/$slug'
    | '/categoria/$slug'
    | '/admin'
    | '/artigos'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin'
    | '/aviso-de-afiliados'
    | '/como-pesquisamos'
    | '/contato'
    | '/mcp'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/login'
    | '/artigos/$slug'
    | '/categoria/$slug'
    | '/admin/'
    | '/artigos/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRouteWithChildren
  AvisoDeAfiliadosRoute: typeof AvisoDeAfiliadosRoute
  ComoPesquisamosRoute: typeof ComoPesquisamosRoute
  ContatoRoute: typeof ContatoRoute
  McpRoute: typeof McpRoute
  PoliticaDeCookiesRoute: typeof PoliticaDeCookiesRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ArtigosSlugRoute: typeof ArtigosSlugRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  ArtigosIndexRoute: typeof ArtigosIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-de-afiliados': {
      id: '/aviso-de-afiliados'
      path: '/aviso-de-afiliados'
      fullPath: '/aviso-de-afiliados'
      preLoaderRoute: typeof AvisoDeAfiliadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-pesquisamos': {
      id: '/como-pesquisamos'
      path: '/como-pesquisamos'
      fullPath: '/como-pesquisamos'
      preLoaderRoute: typeof ComoPesquisamosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-cookies': {
      id: '/politica-de-cookies'
      path: '/politica-de-cookies'
      fullPath: '/politica-de-cookies'
      preLoaderRoute: typeof PoliticaDeCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/artigos/': {
      id: '/artigos/'
      path: '/artigos'
      fullPath: '/artigos/'
      preLoaderRoute: typeof ArtigosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artigos/$slug': {
      id: '/artigos/$slug'
      path: '/artigos/$slug'
      fullPath: '/artigos/$slug'
      preLoaderRoute: typeof ArtigosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRouteWithChildren,
  AvisoDeAfiliadosRoute: AvisoDeAfiliadosRoute,
  ComoPesquisamosRoute: ComoPesquisamosRoute,
  ContatoRoute: ContatoRoute,
  McpRoute: McpRoute,
  PoliticaDeCookiesRoute: PoliticaDeCookiesRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ArtigosSlugRoute: ArtigosSlugRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  ArtigosIndexRoute: ArtigosIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
