/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ArtigosIndexRouteImport } from './routes/artigos.index'
import { Route as ArtigosSlugRouteImport } from './routes/artigos.$slug'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtigosIndexRoute = ArtigosIndexRouteImport.update({
  id: '/artigos/',
  path: '/artigos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtigosSlugRoute = ArtigosSlugRouteImport.update({
  id: '/artigos/$slug',
  path: '/artigos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sobre': typeof SobreRoute
  '/artigos/$slug': typeof ArtigosSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/artigos/': typeof ArtigosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sobre': typeof SobreRoute
  '/artigos/$slug': typeof ArtigosSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/artigos': typeof ArtigosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sobre': typeof SobreRoute
  '/artigos/$slug': typeof ArtigosSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/artigos/': typeof ArtigosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/sobre' | '/artigos/$slug' | '/categoria/$slug' | '/artigos/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sobre' | '/artigos/$slug' | '/categoria/$slug' | '/artigos'
  id:
    | '__root__'
    | '/'
    | '/sobre'
    | '/artigos/$slug'
    | '/categoria/$slug'
    | '/artigos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SobreRoute: typeof SobreRoute
  ArtigosSlugRoute: typeof ArtigosSlugRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  ArtigosIndexRoute: typeof ArtigosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artigos/': {
      id: '/artigos/'
      path: '/artigos'
      fullPath: '/artigos/'
      preLoaderRoute: typeof ArtigosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artigos/$slug': {
      id: '/artigos/$slug'
      path: '/artigos/$slug'
      fullPath: '/artigos/$slug'
      preLoaderRoute: typeof ArtigosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SobreRoute: SobreRoute,
  ArtigosSlugRoute: ArtigosSlugRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  ArtigosIndexRoute: ArtigosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
